name: HolidayItem
version: '${project.version}'
main: me.jake276493.holidayitem.HolidayItem
api-version: '1.20'
authors: [jake276493]
description: Gives customizable items on specified start and end date
commands:
  setdates:
    description: Set time for start and end of event
    usage: /<command>
    permission: holidayitem.setdates
  setitem:
    description: Set the item for the event to be given
    usage: /<command>
    permission: holidayitem.setitem
permissions:
  holidayitem.setdates:
    description: Allows user to set dates for event
  holidayitem.setitem:
    description: Allows user to set the item to be given for event
  holidayitem.*:
    description: All commands and functionality of the plugin
    children:
      holidayitem.setdates: true
      holidayitem.setitem: true